### ISSUE TITLE
issue_votes plugin seems to conflic with redmine_ckeditor plugin

### ISSUE THREAD

**Issue by leoliao** [KohaSuomi/issue_votes#1]
Hello,
first of all, thanks for your plugin creation. I've installed your plugin in my redmine instance, but unfortunately this plugin seems to conflict with redmine_ckeditor....  The Ckeditor toolbar is not getting displayed on the text editor. It can be resolved in case removing issue_vote plugin.
I understood, your plugin is under development, just would like to give you a feedback...

My redmine enviromrnt:
Environment:
  Redmine version                3.0.4.stable
  Ruby version                   2.1.4-p265 (2014-10-27) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Mercurial                      2.0.2
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.5
  extra_queries                  2.0.0
  issue_votes                    0.2.0
  projects_table                 0.0.4
  redmine_agile                  1.3.11
  redmine_ckeditor               1.1.2
  redmine_dmsf                   1.5.3
  redmine_importer               1.2.2
  redmine_issue_tabs             1.1.0
  redmine_lightbox2              0.2.2
  redmine_my_page                0.1.6
  redmine_per_project_formatting 0.0.4
  scrum                          0.12.0

**Comment by jseplae** [comment]
Thanks for letting me know - we don't use the ckeditor internally so I never caught this. This is probably related to how I'm pulling the jquery/javascript dependencies for this plugin.

**Comment by jseplae** [comment]
Hi, 
I'm unable to reproduce this with *only* the 2 plugins installed (issue_votes & ckeditor). You have quite a few other plugins installed - these may need to be investigated. In the meantime - could you provide a screenshot that shows the problem *with* the url of the problem page? I'm going to push a small fix to remove the global plugin js hook that may or may not help with this issue.

**Comment by leoliao** [comment]
Hello,
I have synced your minor fix, it can resolve this issue....so far, working well
Great thanks:- )
