### ISSUE TITLE
The generic user (without permission for vote issue, vote activity, view report) can not watch the amount of vote obtained for the selected issue

### ISSUE THREAD

**Issue by leoliao** [KohaSuomi/issue_votes#2]
Hello, 

I am not sure this is an issue or not, or your original design..  just a feedback. With the latest commit from master, the generic user (who do not have any permission for issue vote plugin(without permission for vote issue, vote activity, view report) can not watch the vote(s) when the user open the single issue detailed view

At least the expectation for the vote feature, the generic user(project member) can watch the amount of vote obtained for the selected issue, even though they do not have permission for vote issue, vote activity, view report

The view with vote issue permission:
![vote_issue_permission](https://cloud.githubusercontent.com/assets/583240/9596894/c29b5bf2-50ad-11e5-82dc-bf2ef0f5983e.png)

The view without any permission in vote issue, vote activity, view report
![without_any_vote_permission](https://cloud.githubusercontent.com/assets/583240/9596918/f8187530-50ad-11e5-96c3-4f286cf66328.png)

My redmine enviromrnt:
Environment:
Redmine version 3.0.4.stable
Ruby version 2.1.4-p265 (2014-10-27) [x86_64-linux]
Rails version 4.2.3
Environment production
Database adapter Mysql2
SCM:
Subversion 1.6.17
Mercurial 2.0.2
Git 1.7.9.5
Filesystem

Redmine plugins:
a_common_libs 1.1.5
extra_queries 2.0.0
issue_votes 0.2.0
projects_table 0.0.4
redmine_agile 1.3.11
redmine_ckeditor 1.1.2
redmine_dmsf 1.5.3
redmine_importer 1.2.2
redmine_issue_tabs 1.1.0
redmine_lightbox2 0.2.2
redmine_my_page 0.1.6
redmine_per_project_formatting 0.0.4
scrum 0.12.0

**Comment by jseplae** [comment]
Thanks for the feedback. It is currently working as intended, but now that I think of it, it would seem better if only the voting button was behind a permission check - so without permissions you would only see the votes.

**Comment by kivilahtio** [comment]
Yes, that would be preferable.

Olli-Antti Kivilahti
Järjestelmäkeittäjä
vaarakirjastot.fi
+358 50 449 7763
--Powered by Kubuntu Linux!


On 01.09.2015 10:53, Juhani Seppälä wrote:

Thanks for the feedback. It is currently working as intended, but now that I think of it, it would seem better if only the voting button was behind a permission check - so without permissions you would only see the votes.

**Comment by jseplae** [comment]
The latest commit moves voting functionality behind permissions.
